version: '3'

services:
  producer:
    tty: true
    image: yeyloo/producer-sdtd
    build: ./python/producer/
    command: sh -c "./run_producer.sh"
    container_name: producer
    environment:
      BROKER_NAME: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092

  consumertemp:
    tty: true
    image: oubaydos/consumertemp-sdtd
    build: ./python/consumertemp/
    container_name: consumertemp
    command: python3 consumer.py
    environment:
      BROKER_NAME: my-release-kafka.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092