version: '3'

services:
  producer:
    tty: true
    image: yeyloo/producer-sdtd
    build: ./python/producer/
    command: sh -c "./run_producer.sh"
    container_name: producer
    environment:
      BROKER_NAME: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092


  consumer:
    tty: true
    image: oubaydos/consumer-sdtd
    build: ./python/consumer/
    command: sh -c "./run_consumer.sh"
    container_name: consumer
    environment:
      BROKER_PRODUCER_NAME: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
      BROKER_CONSUMER_NAME: my-release-kafka.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092
      BROKER_SUBSCRIPTION_TOPIC: 'new_subs'
      BROKER_USAGE_TOPIC: 'frequented_tram'
      CASSANDRA_PORT: 10800
      CASSANDRA_URL: '4.tcp.eu.ngrok.io'
      CASSANDRA_KEYSPACE: 'test'
