version: '3'

services:
  pythonapp:
    tty: true
    build: ./python/
    command: sh -c "sleep 123s ; python3 ./python_app.py"
    depends_on:
      - cassandra
    

  cassandra:
    tty: true
    build: ./cassandra/
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
  sample-data:
    tty: true
    build: ./Script/
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/script.sh"]
    volumes:
      - ./script.sh:/script.sh

