version: '3'

services:
  producer:
    tty: true
    image: yeyloo/producer-sdtd
    build: ./python/producer/
    command: sh -c "./run_producer.sh"
    container_name: producer
    environment:
      BROKER_NAME: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092

  consumer:
    tty: true
    image: yeyloo/consumer-sdtd
    build: ./python/consumer/
    command: sh -c "./run_consumer.sh"
    container_name: consumer
    environment:
      BROKER_PRODUCER_NAME: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
      BROKER_CONSUMER_NAME: my-release-kafka.default.svc.cluster.local
      KAFKA_VALIDATION_TOPIC: temp
      BROKER_PORT: 9092
      BROKER_SUBSCRIPTION_TOPIC: 'new_subs'
      BROKER_USAGE_TOPIC: 'frequented_tram'
      CASSANDRA_PORT: 9042
      CASSANDRA_URL_NODE_0: '10.240.0.70'
      CASSANDRA_URL_NODE_1: '10.240.0.71'
      CASSANDRA_URL_NODE_2: '10.240.0.72'
      CASSANDRA_KEYSPACE: 'test'
  app:
    tty: true
    image: yeyloo/app-sdtd
    build: ./app/
    command: sh -c "python service.py"
    #sleep 130;
    container_name: app
    ports:
      - "8000:8000"
    labels:
      kompose.service.type: nodeport
      kompose.service.nodeport.port: 31000
    environment:
      BROKER_NAME: 'my-release-kafka.default.svc.cluster.local'
      BROKER_PORT: 9092
      BROKER_SUBSCRIPTION_TOPIC: 'new_subs'
      BROKER_USAGE_TOPIC: 'frequented_tram'
      CASSANDRA_URL_NODE_0: '10.240.0.70'
      CASSANDRA_URL_NODE_1: '10.240.0.71'
      CASSANDRA_URL_NODE_2: '10.240.0.72'
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: 'test'
