apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.nodeport.port: "31000"
    kompose.service.type: nodeport
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "8000"
      nodePort: 31000
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: app
  type: NodePort
status:
  loadBalancer: {}
