apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -v convert -f .\docker-compose.yaml -o deployment
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -v convert -f .\docker-compose.yaml -o deployment
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./run_consumer.sh
          env:
            - name: BROKER_CONSUMER_NAME
              value: my-release-kafka.default.svc.cluster.local
            - name: BROKER_PORT
              value: "9092"
            - name: BROKER_PRODUCER_NAME
              value: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
            - name: BROKER_SUBSCRIPTION_TOPIC
              value: new_subs
            - name: BROKER_USAGE_TOPIC
              value: frequented_tram
            - name: CASSANDRA_KEYSPACE
              value: test
            - name: CASSANDRA_PORT
              value: "18907"
            - name: CASSANDRA_URL
              value: 6.tcp.eu.ngrok.io
            - name: KAFKA_VALIDATION_TOPIC
              value: temp
          image: oubaydos/consumer-sdtd
          name: consumer
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
