apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -v convert -f .\docker-compose.yaml -o deployment
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: consumertemp
  name: consumertemp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumertemp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -v convert -f .\docker-compose.yaml -o deployment
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: consumertemp
    spec:
      containers:
        - args:
            - python3
            - consumer.py
          env:
            - name: BROKER_NAME
              value: my-release-kafka.default.svc.cluster.local
            - name: BROKER_PORT
              value: "9092"
            - name: BROKER_SUBSCRIPTION_TOPIC
              value: new_subs
            - name: BROKER_USAGE_TOPIC
              value: frequented_tram
            - name: CASSANDRA_KEYSPACE
              value: test
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_URL
              value: cassandra.default.svc.cluster.local
          image: oubaydos/consumertemp-sdtd
          name: consumertemp
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
