apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./run_producer.sh
          env:
            - name: BROKER_NAME
              value: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local
            - name: BROKER_PORT
              value: "9092"
            - name: KAFKA_VALIDATION_TOPIC
              value: temp
          image: yeyloo/producer-sdtd
          name: producer
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
