import os

KAFKA_PRODUCER_URL = os.getenv('BROKER_PRODUCER_NAME') + ":" + os.getenv('BROKER_PORT')
KAFKA_CONSUMER_URL = os.getenv('BROKER_CONSUMER_NAME') + ":" + os.getenv('BROKER_PORT')
KAFKA_SUBS_TOPIC = os.getenv('BROKER_SUBSCRIPTION_TOPIC')
KAFKA_USAGE_TOPIC = os.getenv('BROKER_USAGE_TOPIC')
CASSANDRA_SERVICE_NAME = [os.getenv('CASSANDRA_URL_NODE_0'), os.getenv('CASSANDRA_URL_NODE_1'),os.getenv('CASSANDRA_URL_NODE_2')]
# CASSANDRA_SERVICE_NAME = 
# CASSANDRA_SERVICE_NAME = 
CASSANDRA_PORT = os.getenv('CASSANDRA_PORT')
CASSANDRA_KEYSPACE = os.getenv('CASSANDRA_KEYSPACE')
KAFKA_VALIDATION_TOPIC = os.getenv('KAFKA_VALIDATION_TOPIC')
